### ISSUE TITLE
Trial version: remaining time check broken?

### ISSUE THREAD

**Issue by ole** [justmakeapp/swiftdeps-distribution#1]
I just downloaded Swift Deps v.1.1.0 from https://github.com/justmakeapp/swiftdeps-distribution/releases/tag/1.1.0. I opened the DMG and moved the app to my Applications folder. On first launch, I get the message that there are 0 minutes remaining in my trial period:

<img width="400" alt="Screenshot 2023-03-29 at 18 37 50" src="https://user-images.githubusercontent.com/5010/228608086-cc3ff15c-eb6d-41d1-9d6f-cd5bea367dc7.png">

Are you aware of this? Is there something broken with the license check?

**Comment by ole** [comment]
The second launch seems to work, so I can indeed try it out. But not the best launch experience. 😀

**Comment by longvudai** [comment]
@ole sorry for your experience. I use paddle SDK to implement this logic, and didn't have the problem you mentioned above during testing. I will try to find a way to reproduce it.
Thank you for taking the time to try the product.

**Comment by ole** [comment]
@longvudai Thanks!
