### ISSUE TITLE
Missing Local Modules ?

### ISSUE THREAD

**Issue by jgodonQobuz** [justmakeapp/swiftdeps-distribution#2]
Hi !

I would like to be able to visualize my local modules as well as I can see the remote packages...

For the moment, only the remote packages are shown... it's a shame because I've bought this app in order to see relations between local  of my modularized project...

Do you think you can do something for it ? If you need any additional comments to understand my issue don't hesitate.

Thanks for your work

Best regards

Jeremie

<img width="723" alt="Capture d’écran 2023-04-02 à 11 21 52" src="https://user-images.githubusercontent.com/114389226/229344148-b12e17b8-5ddd-4d6f-b05a-cfd42c01b7e6.png">
<img width="585" alt="Capture d’écran 2023-04-02 à 11 21 40" src="https://user-images.githubusercontent.com/114389226/229344150-c2029ea7-a98e-4559-be4e-2588146f0be8.png">
<img width="912" alt="Capture d’écran 2023-04-02 à 11 17 12" src="https://user-images.githubusercontent.com/114389226/229344151-f29d7c6a-b729-4ee9-9b3a-612892ae3330.png">

**Comment by longvudai** [comment]
Hi @jgodonQobuz ,

I apologize for the problem you encountered while using our application. As we are still in the early stages of development, it is inevitable that errors may appear during use.

However, we greatly appreciate your feedback and will take care of this issue immediately. Thank you for bringing it to our attention.

**Comment by longvudai** [comment]
Hi @jgodonQobuz ,

Could you please provide us with a minimal example project that reproduces the problem you are encountering? This will help us to better understand the issue and provide you with a more accurate solution.

Thank you in advance for your cooperation.

**Comment by jgodonQobuz** [comment]
Yes no problem, I'll do it tomorrow or the day after

**Comment by jgodon** [comment]
Hi !

Here is a small example... :  [Example.zip](https://github.com/justmakeapp/swiftdeps-distribution/files/11163205/Example.zip)

What I would like to have is something like :

- **Remotes SPM** packages : Nuke, Pulse, swift-dependencies, swift-composable-architecture, etc...

<img width="276" alt="Capture d’écran 2023-04-05 à 23 22 46" src="https://user-images.githubusercontent.com/8012050/230214674-3861ff55-07c6-4843-b8f4-8410e75decf9.png">

- **Local modules** that would be Example, Feature 1, Feature 2, Feature 3

<img width="262" alt="Capture d’écran 2023-04-05 à 23 23 21" src="https://user-images.githubusercontent.com/8012050/230214724-06ea5d92-8007-4e19-b283-dfedc4d60d70.png">

Moreover, I have a few recurrent crashes, as you'll see if you test SwiftDeps with this ExampleApp...

I hope this could help, do not hesitate to contact me if you need more details

Cheers

Jeremie

**Comment by longvudai** [comment]
Thank you for providing more information. I will start fixing bugs right away, please be patient.

**Comment by jgodon** [comment]
Great !
But don't worry, it's not in a hurry 🙂

**Comment by longvudai** [comment]
hi @jgodon ,
I have reviewed your example, and I understand that you would like to explore the dependencies within a particular package, including the relationships between packages, products, targets, and their dependencies. We have this feature on our roadmap, and we are working on developing an algorithm that will allow for easy collapsing and expanding of internal package dependencies. Please be patient, as this feature is coming soon.

**Comment by longvudai** [comment]
I fixed it in https://github.com/justmakeapp/swiftdeps-distribution/releases/tag/1.3.0
please download a new version.
Thank you.

**Comment by jgodonQobuz** [comment]
Thanks a lot @longvudai ! This is a super cool feature for me 👍
Happy to see that this project continues 👏🤞

**Comment by longvudai** [comment]
Thank you for your support and feedback in the first versions.
It helps me make this product better.
Don't hesitate if you want to contribute.
Thanks a lot.
