### ISSUE TITLE
Trial period starts with 0

### ISSUE THREAD

**Issue by kaishin** [justmakeapp/swiftdeps-distribution#3]
I downloaded the app to give a try before buying but I am greeted with a trial expired pop up. I suppose this is not intentional.

**Comment by longvudai** [comment]
> 
Sorry for this inconvenience.
Just kill the app and reopen it. I'll fix this bug as soon as possible.

**Comment by pdshelley** [comment]
The issue is still there. Purchased anyway to try it out.

**Comment by spnkr** [comment]
same issue. I bought it anyway. wish I'd tried force quitting first!

**Comment by longvudai** [comment]
fixed in https://github.com/justmakeapp/swiftdeps-distribution/releases/tag/1.2.2
