### ISSUE TITLE
Error on opening a project - The operation couldn’t be completed. (TSCUtility.Diagnostics error 0.)

### ISSUE THREAD

**Issue by spnkr** [justmakeapp/swiftdeps-distribution#4]
I get this error when I try to open a project. Tried 2, same result.

<img width="621" alt="image" src="https://github.com/justmakeapp/swiftdeps-distribution/assets/11250/1b74816c-bf87-4a61-8865-ca8603fba6c5">

the two projects I tried to open have these strings in their file path: `another-app` and `MY-PROJECT-1`

**Comment by spnkr** [comment]
full logs from the console app: https://gist.github.com/spnkr/bb75c627e0a99ab6357ce171bb21fecb

**Comment by spnkr** [comment]
Btw this is on the paid version of the app, if that matters

**Comment by longvudai** [comment]
Hello Will Jessop,

Sorry for the problem you encountered. We will check it immediately and get back to you as soon as possible.
Please be patient.

Best regards,
Long Vu.

**Comment by longvudai** [comment]
> Btw this is on the paid version of the app, if that matters

Please upgrade to version [1.2.1](https://github.com/justmakeapp/swiftdeps-distribution/releases/tag/1.2.1); I have made it compatible with Swift 5.9.
