### ISSUE TITLE
Error on opening a project – The operation couldn’t be completed. (XcodeProj.XCodeProjError error 1.)

### ISSUE THREAD

**Issue by kaiengelhardt** [justmakeapp/swiftdeps-distribution#5]
When I open my project folder, which contains both and xcodeproj and xcworkspace file, I get the error "The operation couldn’t be completed. (XcodeProj.XCodeProjError error 1.)".
<img width="912" alt="image" src="https://github.com/justmakeapp/swiftdeps-distribution/assets/966076/b052186a-b6fe-4841-a0b4-e8aa9495340c">

Here's the logs from Console.app:
[SwiftDeps Console log.txt](https://github.com/justmakeapp/swiftdeps-distribution/files/12855873/SwiftDeps.Console.log.txt)

An important thing to note is that my Xcode Workspace contains a bunch of Xcode projects, which reside in subfolders of the root project folder. This is a rough sketch of my project structure:
- repo/Project.xcodeproj
- repo/Project.xcworkspace
- repo/Frameworks/Framework1.xcodeproj
- repo/Frameworks/Framework2.xcodeproj

Info:
SwiftDeps version: 1.2.1
macOS version: Sonoma 14.0 (23A344)
Xcode version: 15.0 (15A240d)

**Comment by longvudai** [comment]
@kaiengelhardt thank for your feedback.
I'm going to investigate now

**Comment by longvudai** [comment]
@kaiengelhardt I can not reproduce this bug.
Can you give me an example project that encountered this error?
Thank you.

**Comment by kaiengelhardt** [comment]
> @kaiengelhardt I can not reproduce this bug. Can you give me an example project that encountered this error? Thank you.

Unfortunately the project is under NDA and I cannot share it 😭. Any other way I can give you some diagnostic data from the app?

**Comment by BinaryHammer** [comment]
I have the same problem. But it is the project of my work, I am also not able to share the repository. I also have a workspace and a project file. There is one git submodule. There are subfolders with dependency xcodeproj files.

Maybe a more clearer error message would help.

**Comment by thanhbinh01234** [comment]
> I have the same problem. But it is the project of my work, I am also not able to share the repository. I also have a workspace and a project file. There is one git submodule. There are subfolders with dependency xcodeproj files.
> 
> Maybe a more clearer error message would help.

Hi @BinaryHammer,
Thank you for your feedback. Can you provide some more information about your system, about SwiftDeps version, MacOS version and Xcode version?

**Comment by thanhbinh01234** [comment]
Hi all,
We've just launched a new version to improve the clarity of error parsing for XCode project. Would you mind downloading it, trying again, and then sharing the new error message with us?

**Comment by BinaryHammer** [comment]
@thanhbinh01234 The error is:

> The project doesn't contain a .pbxproj file at path: /path-to-repo/subfolder/swift-package-folder

So SwiftDeps complains that there is no project file in a Swift Package.

**Comment by thanhbinh01234** [comment]
> @thanhbinh01234 The error is:
> 
> 
> 
> > The project doesn't contain a .pbxproj file at path: /path-to-repo/subfolder/swift-package-folder
> 
> 
> 
> So SwiftDeps complains that there is no project file in a Swift Package.

Hi @BinaryHammer,thanks for your valuable information. That helps us a lot for debugging and pinpointing the problem.

**Comment by longvudai** [comment]
@BinaryHammer @kaiengelhardt this issue fixed in https://github.com/justmakeapp/swiftdeps-distribution/releases/tag/1.2.6
please download a new version.
Thanks for all your help
