### ISSUE TITLE
Export to graphviz or mermaid text formats as well as PNG

### ISSUE THREAD

**Issue by woolie** [justmakeapp/swiftdeps-distribution#7]
I'd love to see the app support GraphViz (dot files) and/or mermaid markdown.
Thanks for considering this feature request.

**Comment by longvudai** [comment]
It's very simple, I'll implement it. thank for your feedback.

**Comment by longvudai** [comment]
done in https://github.com/justmakeapp/swiftdeps-distribution/releases/tag/1.4.0
