### ISSUE TITLE
No more Remote Package Updater version update

### ISSUE THREAD

**Issue by jgodonQobuz** [justmakeapp/swiftdeps-distribution#8]
Hello 👋

For a few months now, I can't see remote packages version to update anymore... I miss this Package Updater... 
I don't know why but it never says that a new version of package is available anymore...

Do you have any idea why ? or how to fix this ?

Thanks in advance

<img width="257" alt="Capture d’écran 2024-05-06 à 10 25 40" src="https://github.com/justmakeapp/swiftdeps-distribution/assets/114389226/fe67f910-030b-46b0-8178-242f8a55375b">

**Comment by longvudai** [comment]
hi @jgodonQobuz ,
I will check it out. thank you for your feedback.

**Comment by longvudai** [comment]
fixed in https://github.com/justmakeapp/swiftdeps-distribution/releases/tag/1.4.1 @jgodonQobuz

**Comment by jgodonQobuz** [comment]
Thank you @longvudai 👍
Bug is fixed and I like your promptness 
Have a great day
