### ISSUE TITLE
The operation couldn’t be completed. (TSCUtility.Diagnostics error 0.)

### ISSUE THREAD

**Issue by sisoje** [justmakeapp/swiftdeps-distribution#9]

**Comment by longvudai** [comment]
@sisoje 

Could you please provide us with the following information about your environment?

- The current version of Xcode you are using.
- The output of these commands:
    - /usr/sbin/system_profiler -json SPDeveloperToolsDataType
    - sudo xcode-select -p
    - locale
    - xcrun swift --version
- If available, please send us the project that encountered the error or a minimal viable reproduction (MVP).

**Comment by sisoje** [comment]
@longvudai sorry for missing details. I managed to make it work, but heres details:
I have multiple xcodes: 15.2 and 15.4, The one that gave me error was 15.4 so I had to delete package resolved file then run SwiftDeps and it worked. Seems like xcode updated version of the package from "2" to 3" and it gives some problems to swiftdeps

I am very pleased with the swiftdeps app very good! strange that it does not allow manual layout of elements, but auto layout is great

**Comment by longvudai** [comment]
@sisoje 
Thank you for your detailed feedback! I will investigate the problem you encountered with Xcode 15.4. I’m glad to hear that you find the auto layout feature useful, and I appreciate your patience as we work on improving the app.
